# Generated by Django 5.0.2 on 2024-03-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(default=100, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
