# Generated by Django 5.0.2 on 2024-03-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_dog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='цена'),
        ),
    ]
